
[build]
  command = ""
  publish = "."

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/config.js"
  [headers.values]
    Cache-Control = "no-cache"
